import type { NextComponentType } from "next";
import Head from "next/head";

import Header from "../components/Header";

import styles from "../styles/Layout.module.scss";

const Layout: NextComponentType = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>{children}</main>
    </div>
  );
};

export default Layout;
